exclude: ^(LICENSES)

ci:
  autoupdate_schedule: weekly


repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id : check-json
  - id: pretty-format-json
    args: ['--autofix']
  - id: check-merge-conflict
  - id: check-added-large-files
    args: ['--maxkb=2000']